config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'registrations' }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root "groups#index", as: :authenticated_root # Authenticated root path
    get '/profile', to: 'users#profile'
    get '/profile/edit', to: 'registrations#edit', as: :edit_profile
    get '/statistics', to: 'users#statistics'
  end

  root "splash#index" # Default root path

  resources :users
  resources :groups, only: [:index, :show, :new, :create, :destroy] do
    resources :expenses, only: [:new, :create, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.role == 'admin'
      can :manage, :all
    elsif user.role == 'user'
      can :manage, Expense, author_id: user.id
      can :manage, Group, user_id: user.id
      can :manage, User, id: user.id
    else
      cannot :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups

  validates :name, presence: true, allow_blank: false, length: { minimum: 3, maximum: 50 }
  validates :amount, presence: true, allow_blank: false, numericality: { greater_than: 0 }
  validates :author_id, presence: true, allow_blank: false

  def self.recent_expenses(group)
    group.expenses.includes(:author).order(created_at: :desc)
  end

  def self.total_expenses(user)
    user.expenses.where(author_id: user.id).sum(:amount)
  end

  def self.total_expenses_by_group(group)
    group.expenses.sum(:amount)
  end

  def self.total_expenses_by_group_and_month(group, month)
    group.expenses.select { |expense| expense.created_at.between?(month.first, month.last) }.sum(&:amount)
  end

  def self.total_expenses_by_month(month)
    Expense.where(created_at: month).sum(:amount)
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses

  before_destroy :destroy_expenses

  validates :name, presence: true, allow_blank: false, length: { minimum: 3, maximum: 50 }
  validates :user_id, presence: true, allow_blank: false
  validates :icon, presence: true, allow_blank: false

  def self.total_groups(user)
    Group.where(user_id: user.id).count(:id)
  end

  def self.recent_groups
    Group.order(created_at: :desc)
  end

  private

  def destroy_expenses
    expenses.each(&:destroy)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :expenses, foreign_key: :author_id, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true, allow_blank: false, length: { minimum: 3, maximum: 50 }
  validates :email, presence: true, allow_blank: false
  validates :password, presence: true, length: { minimum: 6, maximum: 30 }, if: :password_required?

  before_save :set_default_profile_photo

  attr_accessor :current_password, :password_confirmation

  private

  def set_default_profile_photo
    self.profile_photo ||= 'default_profile_photo.svg'
  end

  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_sign_up_params, if: :devise_controller?

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:profile_photo, :name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |user|
      user.permit(:email, :password)
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group

  def new
    @expense = Expense.new
  end

  def create
    @expense = @group.expenses.build(expense_params)
    @expense.author_id = current_user.id
    @expense.groups << @group
    if @expense.save
      flash[:notice] = 'New expense created!'
    else
      flash[:alert] = 'Something went wrong! Failed to create a new expense!'
    end
    redirect_to group_path(@group)
  end

  def destroy
    @expense = @group.expenses.find(params[:id])
    if @expense.destroy
      flash[:notice] = 'Expense deleted!'
    else
      flash[:alert] = 'Something went wrong! Failed to delete the expense!'
    end
    redirect_to group_path(@group)
  end

  private

  def set_group
    @group = current_user.groups.find(params[:group_id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show destroy]

  def index
    @groups = current_user.groups.recent_groups.includes(:expenses)
    @total_expenses_by_group = @groups.map do |group|
      Expense.total_expenses_by_group(group)
    end
  end

  def show
    @expenses = Expense.recent_expenses(@group)
    @total_expense_amount = Expense.total_expenses_by_group(@group)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      flash[:notice] = 'New group created!'
      redirect_to groups_path
    else
      flash[:alert] = 'Something went wrong! Failed to create a new group!'
      render :new
    end
  end

  def destroy
    if @group.destroy
      flash[:notice] = 'Group deleted!'
    else
      flash[:alert] = 'Something went wrong! Failed to delete the group!'
    end
    redirect_to groups_path
  end

  private

  def set_group
    @group = current_user.groups.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    if params[:password].blank? && params[:password_confirmation].blank?
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  private

  def devise_mapping
    request.env['devise.mapping'] ||= Devise.mappings[:user] || Devise.mappings.values.first
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    def after_sign_in_path_for(_resource)
      authenticated_root_path
    end

    def after_sign_out_path_for(_resource)
      root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    @user = current_user
  end

  def statistics
    puts "Current user: #{current_user.inspect}"
    @user = current_user
    @total_groups = Group.total_groups(current_user)
    @total_expenses = Expense.total_expenses(current_user)

    @total_expenses_by_group = @user.groups.includes(:expenses).to_h do |group|
      [group.name, Expense.total_expenses_by_group(group)]
    end

    @total_expenses_by_month = (1..12).to_h do |month|
      date = Date.new(Date.today.year, month)
      [Date::MONTHNAMES[month], Expense.total_expenses_by_month(date.beginning_of_month..date.end_of_month)]
    end

    @total_expenses_by_group_and_month = @user.groups.includes(:expenses).to_h do |group|
      [group.name, (1..12).to_h do |month|
        date = Date.new(Date.today.year, month)
        [Date::MONTHNAMES[month],
         Expense.total_expenses_by_group_and_month(group, date.beginning_of_month..date.end_of_month)]
      end]
    end
  end
end

app/views/expenses/new.html.erb
<div class="wrapper">
  <div class="wrapper-left">
    <div class="back-box">
      <%= link_to group_path(@group) do %>
        <%= image_tag("m/menuBack.svg", class:'icon-small back') %>
      <% end %>
    </div>
    <h1 class="title">
      New expense
    </h1>
    <div class="wrapper-left-bg">
      <%= image_tag("bg/bgPlant2.png") %>
      <%= image_tag("bg/bgResearch.png") %>
    </div>
  </div>
  <div class="wrapper-right">
    <%= form_for([@user, @group, @expense], url: group_expenses_path(@group)) do |f| %>

      <div class="form-inputs">
        <%= f.text_field :name, placeholder: 'Expense Name', autofocus: true, class: 'form-input' , required: true %>
          <%= f.number_field :amount, placeholder: 'Amount in $USD', step: '0.00001', class: 'form-input', required: true %>
      </div>

      <div class="actions">
        <%= f.submit 'Create', class: 'form-submit' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="wrapper">
  <div class="wrapper-left">
    <h1 class="title">Categories</h1>
    <div class="wrapper-left-bg">
      <%= image_tag("bg/bgPlant1.png") %>
    </div>
  </div>
  <div class="wrapper-right">
    <% if @groups.empty? %>
      <p class="empty-message">No categories</p>
    <% else %>
      <ul class="categories">
        <% @groups.each_with_index do |group, index| %>
          <li class="category">
            <%= link_to group_path(group), class:"card" do %>
                <%= image_tag("#{group.icon}",class:"icon icon-large") %>

                  <h2 class="title"><%= group.name %></h2>
                  <p class="creation-date">
                    <%= group.created_at.strftime("%d %b %Y") %>
                  </p>

                <div class="card-price">
                  $<%= @total_expenses_by_group[index] %>
                </div>
            <% end %>
            <div class="card-actions">
              <%= button_to 'Delete', group_path(group),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>

    <div class="box-buttons-actions">
      <%= link_to 'Add a new category', new_group_path, class:'add-button' %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="wrapper">
  <div class="wrapper-left">
    <div class="back-box">
      <%= link_to groups_path do %>
        <%= image_tag("m/menuBack.svg", class:'icon-small back') %>
      <% end %>
    </div>
    <h1>New Category</h1>
    <div class="wrapper-left-bg">
      <%= image_tag("bg/bgPlant1.png") %>
    </div>
  </div>
  <div class="wrapper-right">
    <%= form_for([@group], url: groups_path) do |f| %>
      <div class="form-inputs">
        <%= f.text_field :name, placeholder: 'Category Name', class: 'form-input' %>
        <div>
          <h2 class="form-pictures-label"> Pick an Image </h2>
          <div class="pictures-wrapper">
            <% Dir.glob("app/assets/images/g/*").each do |file| %>
              <div class="category-picture-box">
                <%= f.radio_button :icon, "g/" + file.split('/').last, { checked: false, class: 'iconOption picture-checkbox' } %>
                <%= image_tag("g/" + file.split('/').last, class: 'icon-small') %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
  
      <div class="actions">
        <%= f.submit 'Create', class: 'form-submit' %>
      </div>
    <% end %>
  </div>
</div>

<script>
  var iconOptions = document.getElementsByClassName('iconOption');
  for (var i = 0; i < iconOptions.length; i++) {
    iconOptions[i].addEventListener('change', function() {
      document.getElementById('selectedIcon').src = '/assets/' + this.value;
    });
  }
</script>

app/views/groups/show.html.erb
<div class="wrapper">
  <div class="wrapper-left">
    <div class="back-box">
      <%= link_to groups_path do %>
        <%= image_tag("m/menuBack.svg", class:'icon-small back') %>
      <% end %>
    </div>
    <h1 class="title">Expenses</h1>
    <div class="wrapper-left-bg">
      <%= image_tag("bg/bgPlant2.png") %>
    </div>
  </div>
  <div class="wrapper-right wrapper-expenses">
    <h2 class="title-box">
      <span class="title">
        <%= image_tag("#{@group.icon}",class:"icon icon-normal") %>
        <%= @group.name %>
      </span>
      <span class="card-price">$<%= @total_expense_amount %></span>
    </h1>
    <% if @expenses.empty? %>
      <p class="empty-message">There is nothing here...</p>
    <% else %>
      <ul class="categories">
        <% @expenses.each do |expense| %>
          <li class="category">
            <div class="card-2">
              <h2 class="title"><%= expense.name %></h2>
              <p class="card-price">
                $<%= expense.amount %>
              </p>
              <p class="creation-date">
                <%= expense.created_at.strftime("%d %b %Y at %I:%M%p") %>
              </p>
            </div>
              <div class="card-actions">
                <%= button_to 'Destroy', group_expense_path(@group, expense),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %>
              </div>
          </li>
        <% end %>
      </ul>
    <% end %>

    <div class="box-buttons-actions">
      <%= link_to 'Add a new expense', new_group_expense_path(@group), class:'add-button' %>
    </div>
  </div>
</div>

app/views/layouts/_main_naviguation.html.erb
<nav>
  <ul>
    <li>
      <div class="menu-profile">
        <%= image_tag(current_user.profile_photo, class: "icon icon-large") %>
        <span class="title">
          <%= current_user.name %>
        </span>
      </div>
    </li>
    <li>
      <%= link_to root_path, class: 'menu-item-link' do %>
        <%= image_tag("m/menuHome.svg", class:'icon-small menu-img') %>
        <span class="title">
          Home
        </span>
      <% end %>
    </li>
    <li>
      <%= link_to statistics_path, class: 'menu-item-link' do %>
        <%= image_tag("m/menuStatistic.svg", class:'icon-small menu-img') %>
        <span class="title">
          Statistics
        </span>
      <% end %>
    </li>
    <li>
      <%= link_to profile_path, class: 'menu-item-link' do %>
        <%= image_tag("m/menuSettings.svg", class:'icon-small menu-img') %>
        <span class="title">
          Profile
        </span>
      <% end %>
    </li>
  </ul>
  <div class="box-buttons-actions">
    <%= button_to 'Log out', destroy_user_session_path, method: :delete, class:'add-button' %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyTally</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="app-alert-box" data-controller="alert">
      <%= alert %>
      <%= notice %>
    </div>
    <% if user_signed_in? %>
      <%= button_tag(class:'menu-button', data: { action: "click->menu#toggle" }) do %>
      <%= image_tag("m/menuButton.svg", class:'icon-small') %>
    <% end %>
      <header class="menu">
        <%= button_tag(class:'menu-close-button', data: { action: "click->menu#toggle" }) do %>
          <%= image_tag("m/menuClose.svg", class:'icon-small') %>
        <% end %>
        <%= render 'layouts/main_naviguation' %>
      </header>
    <% end %>
    <main>
      <%= yield %>
    </main>

    <% if alert %>
      <script>
        document.querySelector(".app-alert-box").classList.add("active");
        setTimeout(() => {
          document.querySelector(".app-alert-box").classList.remove("active");
        }, 5000);
      </script>
    <% end %>

    <% if notice %>
      <script>
        document.querySelector(".app-alert-box").classList.add("active");
        setTimeout(() => {
          document.querySelector(".app-alert-box").classList.remove("active");
        }, 5000);
      </script>
    <% end %>

    <script>
      const menuElement = document.querySelector(".menu");
      document.querySelector(".menu-button").addEventListener("click", (e) => {
        menuElement.classList.toggle("active");
      });

      document.querySelector(".menu-close-button").addEventListener("click", (e) => {
        menuElement.classList.remove("active");
      });

      document.querySelectorAll(".menu-item-link").forEach((item) => {
        item.addEventListener("click", (e) => {
          menuElement.classList.remove("active");
        });
      });
    </script>
  </body>
</html>

app/views/splash/index.html.erb
<div class="wrapper">
  <div class="wrapper-left wrapper-guest">
    <h1 class="splash-logo title-guest">Money<span>Tally</span></h1>
  </div>
  <div class="wrapper-right wrapper-guest">
    <%= link_to 'Log in' , new_user_session_path, class: 'button splash-button' %>
    <%= link_to 'Sign up' , new_user_registration_path, class: 'button splash-button' %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="wrapper">
  <div class="wrapper-left">
    <div class="back-box">
      <%= link_to groups_path do %>
        <%= image_tag("m/menuBack.svg", class:'icon-small back') %>
      <% end %>
    </div>
    <h1 class="title">Profile</h1>
    <div class="wrapper-left-bg">
      <%= image_tag("bg/bgSpace.png") %>
    </div>
  </div>
  <div class="wrapper-right">
    <div class="profil-card">
      <div class="profile-card-header">
        <div class="img-box">
          <%= image_tag(current_user.profile_photo) %>
        </div>
        <%= link_to( 'Edit Profile' , edit_profile_path , class:'add-button')%>
      </div>
      <div class="profile-card-body">
        <p>
         <b>
            <%= current_user.name %>
          </b>
        </p>
        <p>
          <b>
            <%= current_user.email %>
          </b>
          <br>
          <span>Email</span>
        </p>
        <p>
          <b>
            <%= current_user.created_at.strftime("%d %b %Y") %>
          </b>
          <br>
          <span>Created at</span>
        </p>
      </div>
    </div>
</div>

app/views/users/statistics.html.erb
<div class="wrapper">
  <div class="wrapper-left">
    <div class="back-box">
      <%= link_to groups_path do %>
        <%= image_tag("m/menuBack.svg", class:'icon-small back') %>
      <% end %>
    </div>
    <h1 class="title">Statistics</h1>
    <div class="wrapper-left-bg">
      <%= image_tag("bg/bgResearch.png") %>
      <%= image_tag("bg/bgStatistics.png") %>
    </div>
  </div>
  <div>
    <div class="stats">
      <p>
        Total Categories created: <b><%= @total_groups %></b>
      </p>
      
      <p>
        Total Expenses: <b>$<%= @total_expenses %></b>
      </p>
    </div>

    <div class="stats">
      <div>
        <h2>Total Expenses by Category:</h2>
        <%= pie_chart @total_expenses_by_group, loading: "Loading..." , empty: "No data" %>
      </div>
      <br>
      <div>
        <h2>Total Expenses by Month:</h2>
        <%= area_chart @total_expenses_by_month, loading: "Loading..." , empty: "No data" %>
      </div>
    </div>
  </div>
</div>